# Generated by Django 4.0.2 on 2022-02-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=9, verbose_name='RG')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('federado', models.BooleanField(default=False, verbose_name='Federedo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.teams')),
            ],
        ),
    ]
