# Generated by Django 4.0.2 on 2022-02-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_teams_coaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='coaches',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.coach'),
        ),
    ]
